library(reshape)
setwd("/Users/XW/Desktop/ExData_Plotting1")
data <- read.table(pipe('grep "^[1-2]/2/2007" "household_power_consumption.txt"'), sep = ";", header = F)
names <- read.table("household_power_consumption.txt", nrows = 1, sep = ";")
colnames(data) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
data$DateTime <- paste(data$Date, data$Time)
data$DateTime <- strptime(data$DateTime, "%d/%m/%Y %H:%M:%S")
mdata <- melt(data[,c("DateTime","Sub_metering_1","Sub_metering_2","Sub_metering_3")], id = "DateTime")
png("plot3.png", width = 480, height = 480)
attach(mdata)
plot(DateTime, value, type = "n", ylab = "Energy sub metering", xlab = "")
lines(DateTime[variable=="Sub_metering_1"], value[variable=="Sub_metering_1"], col = "black")
lines(DateTime[variable=="Sub_metering_2"], value[variable=="Sub_metering_2"], col = "red")
lines(DateTime[variable=="Sub_metering_3"], value[variable=="Sub_metering_3"], col = "blue")
legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black", "red", "blue"), lty=1, cex = 0.75)
dev.off()
